name: API Tests

on:
  push:
    branches: [ main, develop, postman-API-test-pipeline]
    paths:
      - 'server/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'server/**'
  workflow_dispatch:

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v2

      - name: Start services with Docker Compose
        run: |
          docker compose -f docker-compose.dev.yml up -d
          # wait for DB & API to be ready
          sleep 15

      - name: Run Postman collection
        run: |
          npm install -g newman
          newman run server/tests/postman/postman_collection.json \
            -e server/tests/postman/postman_environment.json \
            --reporters cli,junit \
            --reporter-junit-export server/tests/postman/results.xml

      - name: Tear down Docker Compose
        run: docker-compose -f server/docker-compose.dev.yml down