name: API Tests

on:
  push:
    branches: [ main, develop, postman-API-test-pipeline]
    paths:
      - 'server/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'server/**'
  workflow_dispatch:

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential curl

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Configure Poetry
        run: |
          poetry config virtualenvs.create false

      - name: Change to server directory and install dependencies
        working-directory: ./server
        run: |
          poetry install --no-root

      # Step 2: Set up Node (required for Newman)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install Newman
      - name: Install Newman
        run: npm install -g newman

      # Step 4: Run Postman collection
      - name: Run API tests
        run: |
          newman run server/tests/postman/postman_collection.json \
          -e server/tests/postman/postman_environment.json \
          --reporters cli,junit \
          --reporter-junit-export server/tests/postman/results.xml

      # Step 5: Optionally upload JUnit report for GitHub Actions
#      - name: Upload test results
#        uses: actions/upload-artifact@v3
#        with:
#          name: newman-results
#          path: results.xml
