name: Run Tests and Lint

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'server/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential curl

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Configure Poetry
        run: |
          poetry config virtualenvs.create false

      - name: Change to server directory and install dependencies
        working-directory: ./server
        run: |
          poetry install --no-root

      - name: Run Pylint
        working-directory: ./server
        run: |
          poetry run pylint app --exit-zero

      - name: Run tests with pytest
        working-directory: ./server
        run: |
          poetry run pytest -v